#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

###### racc/parser.rb begin
unless $".index 'racc/parser.rb'
$".push 'racc/parser.rb'
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
  #
# $Id$
#
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#

unless defined?(NotImplementedError)
  NotImplementedError = NotImplementError
end

module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError
end

module Racc

  unless defined?(Racc_No_Extentions)
    Racc_No_Extentions = false
  end

  class Parser

    old_verbose, $VERBOSE = $VERBOSE, nil
    Racc_Runtime_Version = '1.4.6'
    Racc_Runtime_Revision = '$Id$'

    Racc_Runtime_Core_Version_R = '1.4.6'
    Racc_Runtime_Core_Revision_R = '$Id$'.split[1]
    begin
      require 'racc/cparse'
    # Racc_Runtime_Core_Version_C  = (defined in extention)
      Racc_Runtime_Core_Revision_C = Racc_Runtime_Core_Id_C.split[2]
      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extentions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c
      Racc_YY_Parse_Method         = :_racc_yyparse_c
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C
      Racc_Runtime_Core_Revision   = Racc_Runtime_Core_Revision_C
      Racc_Runtime_Type            = 'c'
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Core_Revision   = Racc_Runtime_Core_Revision_R
      Racc_Runtime_Type            = 'ruby'
    end
    $VERBOSE = old_verbose

    def Parser.racc_runtime_type
      Racc_Runtime_Type
    end

    private

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    ###
    ### do_parse
    ###

    def do_parse
      __send__(Racc_Main_Parsing_Routine, _racc_setup(), false)
    end

    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      goto_table,   goto_check,   goto_default,   goto_pointer,
      nt_base,      reduce_table, token_table,    shift_n,
      reduce_n,     use_result,   * = arg

      _racc_init_sysvars
      tok = act = i = nil
      nerr = 0

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    ###
    ### yyparse
    ###

    def yyparse(recv, mid)
      __send__(Racc_YY_Parse_Method, recv, mid, _racc_setup(), true)
    end

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      goto_table,   goto_check,   goto_default,   goto_pointer,
      nt_base,      reduce_table, token_table,    shift_n,
      reduce_n,     use_result,   * = arg

      _racc_init_sysvars
      nerr = 0

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, action_default, action_pointer,
      goto_table,   goto_check,   goto_default,   goto_pointer,
      nt_base,      reduce_table, token_table,    shift_n,
      reduce_n,     use_result,   * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t == 1   # error token
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      action_table, action_check, action_default, action_pointer,
      goto_table,   goto_check,   goto_default,   goto_pointer,
      nt_base,      reduce_table, token_table,    shift_n,
      reduce_n,     use_result,   * = arg
      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    def on_error(t, val, vstack)
      raise ParseError, sprintf("\nparse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    def yyerror
      throw :racc_jump, 1
    end

    def yyaccept
      throw :racc_jump, 2
    end

    def yyerrok
      @racc_error_status = 0
    end

    #
    # for debugging output
    #

    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"

      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end

#
# parser.rb
#
# Copyright (c) 1998-2007 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the terms of
# the GNU Lesser General Public License version 2.1.
#

require 'tmail/scanner'
require 'tmail/utils'

module TMail
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 341)

  include TextUtils

  def self.parse( ident, str, cmt = nil )
    new.parse(ident, str, cmt)
  end

  MAILP_DEBUG = false

  def initialize
    self.debug = MAILP_DEBUG
  end

  def debug=( flag )
    @yydebug = flag && Racc_debug_parser
    @scanner_debug = flag
  end

  def debug
    @yydebug
  end

  def parse( ident, str, comments = nil )
    @scanner = Scanner.new(str, ident, comments)
    @scanner.debug = @scanner_debug
    @first = [ident, ident]
    result = yyparse(self, :parse_in)
    comments.map! {|c| to_kcode(c) } if comments
    result
  end

  private

  def parse_in( &block )
    yield @first
    @scanner.scan(&block)
  end

  def on_error( t, val, vstack )
    raise SyntaxError, "parse error on token #{racc_token2str t}"
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
   -69,    23,    25,   146,   147,    29,    31,   106,   107,    16,
    17,    19,    22,   137,    23,    25,   -69,    32,    29,    31,
   -69,   154,    16,    17,    19,    22,   -69,    27,    76,    76,
    32,    23,    25,   155,   100,    29,    31,   143,   144,    16,
    17,    19,    22,   108,    27,    23,    25,    32,    99,    29,
    31,   115,   116,    16,    17,    19,    22,   110,    27,    97,
    76,    32,    23,    25,   121,    95,    29,    31,   113,    79,
    16,    17,    19,    22,    92,    27,    23,    25,    32,   118,
    29,    31,    89,    82,    16,    17,    19,    22,   124,    23,
    25,   100,    32,    29,    31,   126,   127,    16,    17,    19,
    22,    81,    27,    23,    25,    32,    92,    29,    31,   129,
   130,    16,    17,    19,    22,    76,    52,    23,    25,    32,
    76,    29,    31,   131,    80,    16,    17,    19,    22,    79,
    23,    25,   134,    32,    29,    31,    79,    78,    16,    17,
    19,    22,    76,    23,    25,    65,    32,    29,    31,    62,
   140,    16,    17,    19,    22,    76,    23,    25,    60,    32,
    29,    31,   100,    44,    16,    17,    19,    22,    76,    23,
    25,   121,    32,    29,    31,   148,   149,    16,    17,    19,
    22,   152,    27,    23,    25,    32,    68,    29,    31,   153,
    42,    16,    17,    19,    22,   157,    27,    23,    25,    32,
   159,    29,    31,    74,    40,    16,    17,    19,    22,    15,
    23,    25,   164,    32,    29,    31,    40,   166,    16,    17,
    19,    22,   167,    27,    23,    25,    32,   nil,    29,    31,
   nil,   nil,    16,    17,    19,    22,   nil,    23,    25,   nil,
    32,    29,    31,   nil,   nil,    16,    17,    19,    22,   nil,
    23,    25,   nil,    32,    29,    31,   nil,   nil,    16,    17,
    19,    22,   nil,    27,    23,    25,    32,   nil,    29,    31,
    74,   nil,    16,    17,    19,    22,   nil,   nil,    93,   nil,
    32,    23,    25,   nil,   nil,    29,    31,   nil,   nil,    16,
    17,    19,    22,   nil,    23,    25,   nil,    32,    29,    31,
   nil,   nil,    16,    17,    19,    22,   nil,    85,    25,   nil,
    32,    29,    31,   nil,    88,    16,    17,    19,    22,    85,
    25,   nil,   nil,    29,    31,   nil,    88,    16,    17,    19,
    22,     4,     6,     7,     8,     9,    10,    11,    12,    13,
     1,     2,     3,    85,    25,   nil,   nil,    29,    31,   nil,
    88,    16,    17,    19,    22,    85,    25,   nil,   nil,    29,
    31,   nil,    88,    16,    17,    19,    22,    85,    25,   nil,
   nil,    29,    31,   nil,    88,    16,    17,    19,    22,    85,
    25,   nil,   nil,    29,    31,   nil,    88,    16,    17,    19,
    22,    85,    25,   nil,   nil,    29,    31,   nil,    88,    16,
    17,    19,    22 ]

racc_action_check = [
    28,    77,    77,   137,   137,    77,    77,    72,    72,    77,
    77,    77,    77,   127,     2,     2,    28,    77,     2,     2,
    28,   144,     2,     2,     2,     2,    28,     2,    67,    28,
     2,     3,     3,   144,    66,     3,     3,   135,   135,     3,
     3,     3,     3,    73,     3,   152,   152,     3,    62,   152,
   152,    87,    87,   152,   152,   152,   152,    75,   152,    60,
    87,   152,    91,    91,    91,    56,    91,    91,    81,    51,
    91,    91,    91,    91,    50,    91,    71,    71,    91,    90,
    71,    71,    45,    42,    71,    71,    71,    71,    97,     7,
     7,    98,    71,     7,     7,    99,   100,     7,     7,     7,
     7,    41,     7,     8,     8,     7,   103,     8,     8,   105,
   106,     8,     8,     8,     8,   109,     8,     9,     9,     8,
   112,     9,     9,   113,    40,     9,     9,     9,     9,    36,
    10,    10,   118,     9,    10,    10,   122,    33,    10,    10,
    10,    10,    70,   155,   155,    13,    10,   155,   155,    12,
   131,   155,   155,   155,   155,   133,    95,    95,    11,   155,
    95,    95,   136,     6,    95,    95,    95,    95,   139,   128,
   128,   128,    95,   128,   128,   140,   141,   128,   128,   128,
   128,   142,   128,    26,    26,   128,    26,    26,    26,   143,
     5,    26,    26,    26,    26,   148,    26,    27,    27,    26,
   151,    27,    27,    27,     4,    27,    27,    27,    27,     1,
    68,    68,   157,    27,    68,    68,   159,   163,    68,    68,
    68,    68,   164,    68,   123,   123,    68,   nil,   123,   123,
   nil,   nil,   123,   123,   123,   123,   nil,    55,    55,   nil,
   123,    55,    55,   nil,   nil,    55,    55,    55,    55,   nil,
    38,    38,   nil,    55,    38,    38,   nil,   nil,    38,    38,
    38,    38,   nil,    38,    52,    52,    38,   nil,    52,    52,
    52,   nil,    52,    52,    52,    52,   nil,   nil,    52,   nil,
    52,   102,   102,   nil,   nil,   102,   102,   nil,   nil,   102,
   102,   102,   102,   nil,    59,    59,   nil,   102,    59,    59,
   nil,   nil,    59,    59,    59,    59,   nil,   115,   115,   nil,
    59,   115,   115,   nil,   115,   115,   115,   115,   115,    89,
    89,   nil,   nil,    89,    89,   nil,    89,    89,    89,    89,
    89,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,   114,   114,   nil,   nil,   114,   114,   nil,
   114,   114,   114,   114,   114,    44,    44,   nil,   nil,    44,
    44,   nil,    44,    44,    44,    44,    44,    78,    78,   nil,
   nil,    78,    78,   nil,    78,    78,    78,    78,    78,    74,
    74,   nil,   nil,    74,    74,   nil,    74,    74,    74,    74,
    74,   130,   130,   nil,   nil,   130,   130,   nil,   130,   130,
   130,   130,   130 ]

racc_action_pointer = [
   329,   178,     0,    17,   189,   190,   145,    75,    89,   103,
   116,   144,   118,   114,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   169,   183,     0,   nil,
   nil,   nil,   nil,   117,   nil,   nil,   103,   nil,   236,   nil,
   108,    87,    83,   nil,   341,    63,   nil,   nil,   nil,   nil,
    58,    43,   250,   nil,   nil,   223,    49,   nil,   nil,   280,
    30,   nil,    16,   nil,   nil,   nil,     8,    -1,   196,   nil,
   113,    62,    -9,    15,   365,    28,   nil,   -13,   353,   nil,
   nil,    53,   nil,   nil,   nil,   nil,   nil,    31,   nil,   305,
    57,    48,   nil,   nil,   nil,   142,   nil,    74,    65,    64,
    65,   nil,   267,    90,   nil,    81,    90,   nil,   nil,    86,
   nil,   nil,    91,   109,   329,   293,   nil,   nil,   117,   nil,
   nil,   nil,   110,   210,   nil,   nil,   nil,   -20,   155,   nil,
   377,   136,   nil,   126,   nil,    14,   136,   -27,   nil,   139,
   158,   161,   156,   174,     6,   nil,   nil,   nil,   181,   nil,
   nil,   174,    31,   nil,   nil,   129,   nil,   195,   nil,   201,
   nil,   nil,   nil,   189,   208,   nil,   nil,   nil ]

racc_action_default = [
  -110,  -110,  -110,  -110,   -14,  -110,   -20,  -110,  -110,  -110,
  -110,  -110,  -110,  -110,   -10,   -96,  -106,  -107,   -44,  -108,
   -78,   -11,  -109,   -80,   -43,  -103,  -110,  -110,   -60,  -104,
   -55,  -105,   -79,   -68,   -54,   -71,   -45,   -12,  -110,    -1,
  -110,  -110,  -110,    -2,  -110,   -22,   -51,   -48,   -50,    -3,
   -40,   -41,  -110,   -46,    -4,   -87,    -5,   -89,    -6,   -91,
  -110,    -7,   -96,    -8,    -9,   -99,  -101,   -61,   -59,   -56,
   -69,  -110,  -110,  -110,  -110,   -77,   -75,   -70,  -110,   -57,
   -15,  -110,   168,   -73,   -81,   -83,   -21,   -24,   -82,  -110,
   -27,  -110,   -84,   -47,   -90,  -110,   -92,  -110,  -101,  -110,
  -102,  -100,  -110,   -58,   -52,  -110,  -110,   -64,   -63,   -65,
   -76,   -72,   -67,  -110,  -110,  -110,   -26,   -23,  -110,   -29,
   -49,   -85,   -42,   -88,   -93,   -95,   -96,  -110,  -110,   -62,
  -110,  -110,   -74,   -25,   -28,   -31,  -101,  -110,   -53,   -66,
  -110,  -110,   -34,  -110,  -110,   -94,   -97,   -98,  -110,   -18,
   -13,   -38,  -110,   -30,   -33,  -110,   -32,   -16,   -19,   -14,
   -35,   -36,   -37,  -110,  -110,   -39,   -86,   -17 ]

racc_goto_table = [
    39,    67,    70,    73,    38,    66,    69,    24,    37,    57,
    59,    36,    55,    67,    91,    84,   109,    86,    69,   101,
   112,   158,    77,    49,    53,   135,   142,    70,    73,   151,
   119,    90,    45,   156,   160,   150,   141,    21,    14,    18,
   120,   103,    64,    63,    61,    84,    70,   105,    58,    84,
   132,   125,    98,    56,    54,    94,    43,   133,     5,    96,
    84,   102,   117,   nil,    77,   nil,   nil,   128,   nil,    38,
   nil,   nil,   139,   104,   nil,   nil,   nil,   111,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    84,    84,   nil,   nil,   145,
   nil,   nil,   nil,   nil,   nil,    57,   nil,   nil,   123,   nil,
   122,    84,   111,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   136,   nil,   nil,   nil,
   nil,   nil,   nil,    94,   nil,   nil,   nil,    70,   162,    38,
    70,   163,   161,   138,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   165 ]

racc_goto_check = [
     2,    37,    37,    29,    36,    47,    28,    13,    13,    42,
    42,    31,    46,    37,    32,    45,    25,    24,    28,    48,
    25,    23,    41,     4,     4,    20,    21,    37,    29,    22,
    19,    18,    17,    26,    27,    16,    15,    12,    11,    33,
    34,    35,    10,     9,     8,    45,    37,    29,     7,    45,
    43,    48,    47,     6,     5,    42,     3,    25,     1,    42,
    45,    41,    24,   nil,    41,   nil,   nil,    32,   nil,    36,
   nil,   nil,    25,    13,   nil,   nil,   nil,    42,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    45,    45,   nil,   nil,    48,
   nil,   nil,   nil,   nil,   nil,    42,   nil,   nil,    46,   nil,
    31,    45,    42,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    47,   nil,   nil,   nil,
   nil,   nil,   nil,    42,   nil,   nil,   nil,    37,    29,    36,
    37,    29,    28,    13,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,    58,    -4,    50,    16,    46,    44,    38,    33,    31,
    29,    37,    35,     5,   nil,   -95,  -106,    26,   -14,   -60,
   -94,  -109,  -113,  -130,   -27,   -58,  -111,  -118,   -20,   -24,
   nil,     9,   -36,    37,   -51,   -27,     1,   -25,   nil,   nil,
   nil,    -6,     0,   -64,   nil,   -29,     3,   -10,   -47 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    48,    41,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    87,   nil,   nil,    30,    34,
    50,    51,   nil,    46,    47,   nil,    26,    28,    71,    72,
    33,   114,    35,    83,    75,    20,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 35, :_reduce_1,
  2, 35, :_reduce_2,
  2, 35, :_reduce_3,
  2, 35, :_reduce_4,
  2, 35, :_reduce_5,
  2, 35, :_reduce_6,
  2, 35, :_reduce_7,
  2, 35, :_reduce_8,
  2, 35, :_reduce_9,
  2, 35, :_reduce_10,
  2, 35, :_reduce_11,
  2, 35, :_reduce_12,
  6, 36, :_reduce_13,
  0, 48, :_reduce_none,
  2, 48, :_reduce_none,
  3, 49, :_reduce_16,
  5, 49, :_reduce_17,
  1, 50, :_reduce_18,
  7, 37, :_reduce_19,
  0, 51, :_reduce_none,
  2, 51, :_reduce_21,
  0, 52, :_reduce_none,
  2, 52, :_reduce_23,
  1, 58, :_reduce_24,
  3, 58, :_reduce_25,
  2, 58, :_reduce_26,
  0, 53, :_reduce_none,
  2, 53, :_reduce_28,
  0, 54, :_reduce_29,
  3, 54, :_reduce_30,
  0, 55, :_reduce_none,
  2, 55, :_reduce_32,
  2, 55, :_reduce_33,
  0, 56, :_reduce_none,
  2, 56, :_reduce_35,
  1, 61, :_reduce_36,
  1, 61, :_reduce_37,
  0, 57, :_reduce_none,
  2, 57, :_reduce_39,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  3, 38, :_reduce_none,
  1, 46, :_reduce_none,
  1, 46, :_reduce_none,
  1, 46, :_reduce_none,
  1, 39, :_reduce_none,
  2, 39, :_reduce_47,
  1, 64, :_reduce_48,
  3, 64, :_reduce_49,
  1, 68, :_reduce_none,
  1, 68, :_reduce_none,
  1, 69, :_reduce_52,
  3, 69, :_reduce_53,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  2, 47, :_reduce_56,
  2, 67, :_reduce_none,
  3, 65, :_reduce_58,
  2, 65, :_reduce_59,
  1, 70, :_reduce_60,
  2, 70, :_reduce_61,
  4, 62, :_reduce_62,
  3, 62, :_reduce_63,
  2, 72, :_reduce_none,
  2, 73, :_reduce_65,
  4, 73, :_reduce_66,
  3, 63, :_reduce_67,
  1, 63, :_reduce_68,
  1, 74, :_reduce_none,
  2, 74, :_reduce_70,
  1, 71, :_reduce_71,
  3, 71, :_reduce_72,
  1, 59, :_reduce_73,
  3, 59, :_reduce_74,
  1, 78, :_reduce_none,
  2, 78, :_reduce_76,
  1, 75, :_reduce_77,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 66, :_reduce_none,
  2, 66, :_reduce_none,
  3, 60, :_reduce_86,
  1, 40, :_reduce_87,
  3, 40, :_reduce_88,
  1, 80, :_reduce_none,
  2, 80, :_reduce_90,
  1, 41, :_reduce_91,
  2, 41, :_reduce_92,
  3, 42, :_reduce_93,
  5, 43, :_reduce_94,
  3, 43, :_reduce_95,
  0, 81, :_reduce_96,
  5, 81, :_reduce_97,
  5, 81, :_reduce_98,
  1, 44, :_reduce_99,
  3, 45, :_reduce_100,
  0, 82, :_reduce_none,
  1, 82, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none ]

racc_reduce_n = 110

racc_shift_n = 168

racc_token_table = {
  false => 0,
  :error => 1,
  :DATETIME => 2,
  :RECEIVED => 3,
  :MADDRESS => 4,
  :RETPATH => 5,
  :KEYWORDS => 6,
  :ENCRYPTED => 7,
  :MIMEVERSION => 8,
  :CTYPE => 9,
  :CENCODING => 10,
  :CDISPOSITION => 11,
  :ADDRESS => 12,
  :MAILBOX => 13,
  :DIGIT => 14,
  :ATOM => 15,
  "," => 16,
  ":" => 17,
  :FROM => 18,
  :BY => 19,
  "@" => 20,
  :DOMLIT => 21,
  :VIA => 22,
  :WITH => 23,
  :ID => 24,
  :FOR => 25,
  ";" => 26,
  "<" => 27,
  ">" => 28,
  "." => 29,
  :QUOTED => 30,
  :TOKEN => 31,
  "/" => 32,
  "=" => 33 }

racc_nt_base = 34

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DATETIME",
  "RECEIVED",
  "MADDRESS",
  "RETPATH",
  "KEYWORDS",
  "ENCRYPTED",
  "MIMEVERSION",
  "CTYPE",
  "CENCODING",
  "CDISPOSITION",
  "ADDRESS",
  "MAILBOX",
  "DIGIT",
  "ATOM",
  "\",\"",
  "\":\"",
  "FROM",
  "BY",
  "\"@\"",
  "DOMLIT",
  "VIA",
  "WITH",
  "ID",
  "FOR",
  "\";\"",
  "\"<\"",
  "\">\"",
  "\".\"",
  "QUOTED",
  "TOKEN",
  "\"/\"",
  "\"=\"",
  "$start",
  "content",
  "datetime",
  "received",
  "addrs_TOP",
  "retpath",
  "keys",
  "enc",
  "version",
  "ctype",
  "cencode",
  "cdisp",
  "addr_TOP",
  "mbox",
  "day",
  "hour",
  "zone",
  "from",
  "by",
  "via",
  "with",
  "id",
  "for",
  "received_datetime",
  "received_domain",
  "domain",
  "msgid",
  "received_addrspec",
  "routeaddr",
  "spec",
  "addrs",
  "group_bare",
  "commas",
  "group",
  "addr",
  "mboxes",
  "addr_phrase",
  "local_head",
  "routes",
  "at_domains",
  "local",
  "dots",
  "word",
  "domword",
  "dot_repeat",
  "atom",
  "phrase",
  "params",
  "opt_semicolon" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 16)
  def _reduce_1(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_2(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_3(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_4(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_5(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 21)
  def _reduce_6(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_7(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_8(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_9(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_10(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_11(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_12(val, _values)
     val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_13(val, _values)
                      t = Time.gm(val[3].to_i, val[2], val[1].to_i, 0, 0, 0)
                  (t + val[4] - val[5]).localtime

  end
.,.,

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_16(val, _values)
                      (val[0].to_i * 60 * 60) +
                  (val[2].to_i * 60)

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_17(val, _values)
                      (val[0].to_i * 60 * 60) +
                  (val[2].to_i * 60) +
                  (val[4].to_i)

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_18(val, _values)
                      timezone_string_to_unixtime(val[0])

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_19(val, _values)
                      val

  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_21(val, _values)
                      val[1]

  end
.,.,

# reduce 22 omitted

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_23(val, _values)
                      val[1]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_24(val, _values)
                      join_domain(val[0])

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_25(val, _values)
                      join_domain(val[2])

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_26(val, _values)
                      join_domain(val[0])

  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_28(val, _values)
                      val[1]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_29(val, _values)
                      []

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 100)
  def _reduce_30(val, _values)
                      val[0].push val[2]
                  val[0]

  end
.,.,

# reduce 31 omitted

module_eval(<<'.,.,', 'parser.y', 107)
  def _reduce_32(val, _values)
                      val[1]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 111)
  def _reduce_33(val, _values)
                      val[1]

  end
.,.,

# reduce 34 omitted

module_eval(<<'.,.,', 'parser.y', 117)
  def _reduce_35(val, _values)
                      val[1]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_36(val, _values)
                      val[0].spec

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 127)
  def _reduce_37(val, _values)
                      val[0].spec

  end
.,.,

# reduce 38 omitted

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_39(val, _values)
                      val[1]

  end
.,.,

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

module_eval(<<'.,.,', 'parser.y', 146)
  def _reduce_47(val, _values)
     [ Address.new(nil, nil) ]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 150)
  def _reduce_48(val, _values)
                      val

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 154)
  def _reduce_49(val, _values)
                      val[0].push val[2]
                  val[0]

  end
.,.,

# reduce 50 omitted

# reduce 51 omitted

module_eval(<<'.,.,', 'parser.y', 163)
  def _reduce_52(val, _values)
                      val

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 167)
  def _reduce_53(val, _values)
                      val[0].push val[2]
                  val[0]

  end
.,.,

# reduce 54 omitted

# reduce 55 omitted

module_eval(<<'.,.,', 'parser.y', 175)
  def _reduce_56(val, _values)
                      val[1].phrase = Decoder.decode(val[0])
                  val[1]

  end
.,.,

# reduce 57 omitted

module_eval(<<'.,.,', 'parser.y', 183)
  def _reduce_58(val, _values)
                      AddressGroup.new(val[0], val[2])

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 185)
  def _reduce_59(val, _values)
     AddressGroup.new(val[0], [])
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 188)
  def _reduce_60(val, _values)
     val[0].join('.')
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 189)
  def _reduce_61(val, _values)
     val[0] << ' ' << val[1].join('.')
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 193)
  def _reduce_62(val, _values)
                      val[2].routes.replace val[1]
                  val[2]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 198)
  def _reduce_63(val, _values)
                      val[1]

  end
.,.,

# reduce 64 omitted

module_eval(<<'.,.,', 'parser.y', 203)
  def _reduce_65(val, _values)
     [ val[1].join('.') ]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 204)
  def _reduce_66(val, _values)
     val[0].push val[3].join('.'); val[0]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 206)
  def _reduce_67(val, _values)
     Address.new( val[0], val[2] )
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 207)
  def _reduce_68(val, _values)
     Address.new( val[0], nil )
  end
.,.,

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.y', 210)
  def _reduce_70(val, _values)
     (val[1] + 1).times {val[0].push ''}; val[0]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 213)
  def _reduce_71(val, _values)
     val
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 216)
  def _reduce_72(val, _values)
                      val[1].times do
                    val[0].push ''
                  end
                  val[0].push val[2]
                  val[0]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 224)
  def _reduce_73(val, _values)
     val
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 227)
  def _reduce_74(val, _values)
                      val[1].times do
                    val[0].push ''
                  end
                  val[0].push val[2]
                  val[0]

  end
.,.,

# reduce 75 omitted

module_eval(<<'.,.,', 'parser.y', 235)
  def _reduce_76(val, _values)
     val[0] + val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 236)
  def _reduce_77(val, _values)
     val[0].size - 1
  end
.,.,

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

# reduce 85 omitted

module_eval(<<'.,.,', 'parser.y', 251)
  def _reduce_86(val, _values)
                      val[1] = val[1].spec
                  val.join('')

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 255)
  def _reduce_87(val, _values)
     val
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 256)
  def _reduce_88(val, _values)
     val[0].push val[2]; val[0]
  end
.,.,

# reduce 89 omitted

module_eval(<<'.,.,', 'parser.y', 259)
  def _reduce_90(val, _values)
     val[0] << ' ' << val[1]
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 263)
  def _reduce_91(val, _values)
                      val.push nil
                  val

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 268)
  def _reduce_92(val, _values)
                      val

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 273)
  def _reduce_93(val, _values)
                      [ val[0].to_i, val[2].to_i ]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 278)
  def _reduce_94(val, _values)
                      [ val[0].downcase, val[2].downcase, decode_params(val[3]) ]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 282)
  def _reduce_95(val, _values)
                      [ val[0].downcase, nil, decode_params(val[1]) ]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 287)
  def _reduce_96(val, _values)
                      {}

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 291)
  def _reduce_97(val, _values)
                      val[0][ val[2].downcase ] = ('"' + val[4].to_s + '"')
                  val[0]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 296)
  def _reduce_98(val, _values)
                      val[0][ val[2].downcase ] = val[4]
                  val[0]

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 302)
  def _reduce_99(val, _values)
                      val[0].downcase

  end
.,.,

module_eval(<<'.,.,', 'parser.y', 307)
  def _reduce_100(val, _values)
                      [ val[0].downcase, decode_params(val[1]) ]

  end
.,.,

# reduce 101 omitted

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

# reduce 106 omitted

# reduce 107 omitted

# reduce 108 omitted

# reduce 109 omitted

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module TMail
